name: CI

on:
  workflow_dispatch:
  pull_request:
  push:

env:
  FOUNDRY_PROFILE: ci

jobs:
  check:
    strategy:
      fail-fast: true

    name: CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Run Forge build
        run: |
          forge --version
          forge build --sizes
        id: build

      - name: Run Forge tests
        run: |
          ARBITRUM_RPC_URL=${{ secrets.ARBITRUM_RPC_URL }} BASE_RPC_URL=${{ secrets.BASE_RPC_URL }} BLAST_RPC_URL=${{ secrets.BLAST_RPC_URL }} MAINNET_RPC_URL=${{ secrets.MAINNET_RPC_URL }} forge test --gas-report
        id: test

      - name: "Generate coverage report"
        run: "forge coverage --report lcov"
        id: coverage

      - name: "Upload coverage report to Codecov"
        uses: "codecov/codecov-action@v3"
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: "./lcov.info"
          name: insrt-lp-contracts
          verbose: true
